#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Start checking...'

npm run check-types ||
(
  echo 'Failed type check'
  false;
)

npm run check-format ||
(
  echo 'Failed format check'
  false;
)

npm run check-lint ||
(
  echo 'Failed lint check'
  false;
)

npm run build ||
(
  echo 'Failed build'
)

echo 'Everything is fine'