#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit "$1"

echo 'START CHECKING...'

npm run check-types ||
(
  echo 'FAILED TYPE CHECK. Please review your code'
  false;
)

npm run check-format ||
(
  echo 'FAILED FORMAT CHECK. Please review your code'
  false;
)

npm run check-lint ||
(
  echo 'FAILED LINT CHECK. Please review your code'
  false;
)

npm run build ||
(
  echo 'OOOOPSS...something went wrong. BUILD FAILED'
)

echo 'Everything is fine! You can commit your changes'
